# Generated by Django 4.2.11 on 2025-10-20 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_stickers/')),
                ('photo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stickers', to='albums.sticker')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
